const fs = require('fs');
const d = 'astro/dist/';
const ck = (p) => (fs.existsSync(d + p) ? 'OK' : 'MISSING');
let out = '';
out += 'en:' + ck('blog/you-design-it-we-build-it-box-it/index.html') + '\n';
out += 'tr:' + ck('tr/blog/siz-tasarlayin-biz-uretelim/index.html') + '\n';
out += 'ar:' + ck('ar/blog/design-it-build-it-box-it/index.html') + '\n';
const h = fs.readFileSync(d + 'blog/you-design-it-we-build-it-box-it/index.html', 'utf8');
const hl = (h.match(/rel="alternate"[^>]*>/g) || []).join('|');
out += 'HREFLANGS:' + hl + '\n';
const cn = (h.match(/rel="canonical" href="[^"]*"/g) || []).join('|');
out += 'CANONICAL:' + cn + '\n';
const trh = fs.readFileSync(d + 'tr/blog/siz-tasarlayin-biz-uretelim/index.html', 'utf8');
const title = (trh.match(/<title>([^<]*)<\/title>/) || [])[1] || '';
out += 'TR TITLE:' + title + '\n';
const arh = fs.readFileSync(d + 'ar/blog/design-it-build-it-box-it/index.html', 'utf8');
out += 'AR DIR:' + ((arh.match(/<html[^>]*dir="([^"]*)"/) || [])[1] || '') + '\n';
fs.writeFileSync('verify_blog.txt', out);
console.log('written');
