export const locales = ['en'] as const;
export type AppLocale = (typeof locales)[number];
export const defaultLocale = 'en' as const;

export const pathnames = {
  '/': '/',
  '/contact': '/contact',
  '/about': '/about',
  '/about/company-profile': '/about/company-profile',
  '/about/brand-story': '/about/brand-story',
  '/about/manufacturing-capabilities': '/about/manufacturing-capabilities',
  '/about/quality-control': '/about/quality-control',
  '/blog': '/blog',
  '/services': '/services',
  '/services/oem-odm': '/services/oem-odm',
  '/services/product-design': '/services/product-design',
  '/services/production-assembly': '/services/production-assembly',
  '/services/packaging-logistics': '/services/packaging-logistics',
  '/products': '/products',
  '/products/themis': '/products/themis',
  '/products/sapphire': '/products/sapphire',
  '/products/lumi-2': '/products/lumi-2',
  '/products/hestia': '/products/hestia',
  '/products/hebe': '/products/hebe',
  '/products/euno': '/products/euno',
  '/products/emerald': '/products/emerald',
  '/products/eirene': '/products/eirene',
  '/products/alpha': '/products/alpha',
  '/products/wooden': '/products/wooden',
  '/custom-ipl': '/custom-ipl',
  '/custom-ipl/smart-app': '/custom-ipl/smart-app',
  '/custom-ipl/skinsensor': '/custom-ipl/skinsensor',
  '/custom-ipl/packaging': '/custom-ipl/packaging',
  '/custom-ipl/multi-head': '/custom-ipl/multi-head',
  '/custom-ipl/multi-function': '/custom-ipl/multi-function',
  '/custom-ipl/logo-print': '/custom-ipl/logo-print',
  '/custom-ipl/duallamp': '/custom-ipl/duallamp',
  '/custom-ipl/startups': '/custom-ipl/startups',
  '/custom-ipl/men': '/custom-ipl/men',
  '/custom-ipl/globalshipping': '/custom-ipl/globalshipping',
  '/custom-ipl/fda-cleared': '/custom-ipl/fda-cleared',
  '/custom-ipl/expertise': '/custom-ipl/expertise',
  '/custom-ipl/design': '/custom-ipl/design',
  '/custom-ipl/customenery': '/custom-ipl/customenery',
  '/custom-ipl/cooling': '/custom-ipl/cooling',
  '/custom-ipl/compliance': '/custom-ipl/compliance',
  '/custom-ipl/aftersales': '/custom-ipl/aftersales',
  '/components': '/components',
  '/components/lamp-cartridges': '/components/lamp-cartridges',
  '/components/optical-filters': '/components/optical-filters',
  '/components/cooling-system': '/components/cooling-system',
  '/components/power-supply': '/components/power-supply',
  '/sitemap': '/sitemap',
  '/success': '/success',
  '/clients': '/clients',
  '/clients/costco-canada-ipl': '/clients/costco-canada-ipl',
  '/clients/roseskin-ipl': '/clients/roseskin-ipl',
  '/clients/happyskinco-ipl': '/clients/happyskinco-ipl',
  '/clients/ku2-ipl': '/clients/ku2-ipl',
} as const;
